### ISSUE TITLE
Game Setup

### ISSUE THREAD

**Issue by Drew-Wagner** [JonathanSolvesProblems/Warzone-Comp345#12]
### Tasks
- [ ] #13 Select and Load Map Files
- [x] #14 Choose # of players
- [x] #15 Preferences

### Constraints
- [ ] Implementation must be in `GameEngine.cpp/GameEngine.h`
