### ISSUE TITLE
Refactor Orders class (15 points)

### ISSUE THREAD

**Issue by anthony2v** [JonathanSolvesProblems/Warzone-Comp345#24]
### Definition of Done
- [x] [#33](https://github.com/JonathanSolvesProblems/Warzone-Comp345/issues/33) Refactor Order Constructors
- [x] [#31](https://github.com/JonathanSolvesProblems/Warzone-Comp345/issues/31) Refactor Order execute()
- [x] [#32](https://github.com/JonathanSolvesProblems/Warzone-Comp345/issues/32) Refactor Order validate()
