### ISSUE TITLE
Refactor MapLoader File

### ISSUE THREAD

**Issue by th3bigch33s3** [JonathanSolvesProblems/Warzone-Comp345#26]
### Tasks
- [ ] make more methods make sure methods have 1 purpose.
- [ ] adding new methods to the .h file.
- [ ] make data members private, or see if they can all be removed.
- [ ] make sure the code is clean and well organized.
